### ISSUE TITLE
Node Server Locks up

### ISSUE THREAD

**Issue by sjpbailey** [UniversalDevicesInc-PG3/udi-solaredge-poly#1]
Hello All,
 A Python 3.9 lib error, is this on my end or Polisy as Polisy is up to date. 
My localhost is running Python 3.8 which should have no impact on this so i was wondering why it stops working.

It will startup and run for a few days then do this when it locks up:
```
2022-07-25 03:00:06,296 Command    udi_interface      ERROR    udi_interface:write: Exception in thread
2022-07-25 03:00:06,297 Command    udi_interface      ERROR    udi_interface:write: Command
2022-07-25 03:00:06,298 Command    udi_interface      ERROR    udi_interface:write: :
2022-07-25 03:00:06,299 Command    udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-07-25 03:00:06,300 Command    udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
2022-07-25 03:00:06,304 Command    udi_interface      ERROR    udi_interface:write: self.run()
2022-07-25 03:00:06,305 Command    udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 917, in run
2022-07-25 03:00:06,309 Command    udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-07-25 03:00:06,310 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 680, in _parseInput
2022-07-25 03:00:06,314 Command    udi_interface      ERROR    udi_interface:write: self._handleInput(key, input[key], None)
2022-07-25 03:00:06,315 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 811, in _handleInput
2022-07-25 03:00:06,319 Command    udi_interface      ERROR    udi_interface:write: self.nodes_internal[item['address']].query()
2022-07-25 03:00:06,319 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:21:b9:02:53:3c_2/./solaredge-poly.py", line 117, in query
2022-07-25 03:00:06,321 Command    udi_interface      ERROR    udi_interface:write: for node in self.nodes:
2022-07-25 03:00:06,321 Command    udi_interface      ERROR    udi_interface:write: AttributeError
2022-07-25 03:00:06,322 Command    udi_interface      ERROR    udi_interface:write: :
2022-07-25 03:00:06,323 Command    udi_interface      ERROR    udi_interface:write: 'Controller' object has no attribute 'nodes'

```
Restart i get and it runs for a few days:
```
2022-07-26 22:29:46,855 MainThread udi_interface.interface ERROR    interface:_get_server_data: get_server_data: failed to read file server.json: Expecting value: line 25 column 16 (char 789)
Traceback (most recent call last):
  File "/var/polyglot/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 471, in _get_server_data
    self.serverdata = json.load(data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 25 column 16 (char 789)
2022-07-26 22:29:46,864 MainThread udi_interface.interface WARNING  interface:db_getNodeDrivers: controller not found in database.
2022-07-26 22:29:46,865 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection :: {'config': {'version': 'unknown'}}
2022-07-26 22:29:46,907 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Connected with result code 0 (Success)
2022-07-26 22:29:46,909 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Subscribing to topic: udi/pg3/ns/clients/00:21:b9:02:53:3c_2 -  MID: 1 Result: 0
2022-07-26 22:29:46,920 MQTT       udi_interface.interface INFO     interface:_subscribe: MQTT Subscribed Succesfully for Message ID: 1 - QoS: (0,)
2022-07-26 22:29:49,877 MainThread udi_interface.interface INFO     interface:addNode: Adding node SolarEdge Controller(controller) [None]
2022-07-26 22:29:50,183 Thread-1   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2022-07-26 22:29:50,431 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
```

**Comment by bpaauwe** [comment]
If your Polisy is up-to-date then it should be using Python 3.9 which it looks like it is.

version 1.0.1 fixes the error in the server.json.
version 1.0.1 fixes the error when query is called on the controller node.

**Comment by sjpbailey** [comment]
Thank you Bob!
